# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:                  Open Accessibility
description:            Multipurpose Jekyll theme.
url:                    # Site base hostname & protocol, e.g. http://example.com
baseurl:                # Site subpath, e.g. /blog
lang:                   en
logo:                   logo.png
logo_light:             logo.png
permalink:              /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:            "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:                /uploads/ # Path to post content assets directory i.e post images, pdfs etc
template:               base

# paginate:               9 # Number of posts displayed on blog page
# paginate_path:          "/blog/:num/" # Blog path

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
# Default author settings
author:
  name:                 Pete Seth
  avatar:               avatar-tom.png
  title:                Support     
  bio:                  I am the CEO of this company, loved by everyone, just plain awesome so you want to follow me all the time.
  url:
  email:                elias.pajares@tum.de
  website:
  facebook:             https://www.facebook.com/
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:            https://www.instagram.com/
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  john:
    name:               John Brown
    title:              Support     
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"
  evan:
    name:               Evan Wells
    title:              Support    
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"
  sara:
    name:               Sara Galen
    title:              Lead Developer     
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"
  alex:
    title:              Design Engineer     
    name:               Alex Koch
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"
  daniel:
    title:              Developer      
    name:               Daniel Shultz
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"
  tom:
    title:              Developer     
    name:               Tom Farrell
    avatar:             https://via.placeholder.com/380
    bio:                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    twitter:            "#"
    facebook:           "#"
    linkedin:           "#"

navbar:
  layout:               default # default, center
  color:                dark # text color, dark or light
  animation:            true
  sticky:               true
  search:               false

footer:                 # Default footer image settings
  style:                secondary # default, muted, primary, secondary
  layout:               center # center or columns
  copyright:            Open Accessibility 2020 | All Rights Reserved

mailchimp:
  form_action:          000000
  hidden_name:          000000
  
google_analytics:       # Google analytics code, get your code here https://www.google.com/analytics/
google_maps_api_key:    AIzaSyDozvEBl_XAzNqSPT2y1_hlU19REsmxhTE # Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key

disqus:
  shortname:            # Disqus comments shortname, requires Disqus account https://disqus.com/

instagram_accesstoken:  9787042989.1677ed0.1dd0f134cfe84e1d88a05b9afbedec3c

donations:
  paypal:
    id:                 # PayPal button ID
    navbar:             # true

# Social share buttons
social_share:
  twitter:              true
  facebook:             true
  linkedin:             true
  pinterest:            true
  reddit:               true

# Social buttons
social_networks:
  email:                
  website:
  facebook:             
  flickr:
  dribbble:
  github:               https://github.com/goat-community/goat
  googleplus:
  instagram:            
  linkedin:             https://www.linkedin.com/company/goat-tool/
  pinterest:
  twitter:              https://twitter.com/GoatTool
  vimeo:
  youtube:

# Build settings
markdown:               kramdown
highlighter:            rouge
kramdown:
  toc_levels:           "2"

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap

exclude: 
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - config
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
  - Rakefile
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:                compressed

# collections:
collections:
  blocks:
    output:             false
  sidebars:
    output:             false
  docs:
    output:             true
  videos:
    output:             false

# Defaults
defaults:
  # _posts
  - scope:
      path:                 ""
      type:                 posts
    values:
      layout:               post
      section:              large
      width:                small
      # sidebar: 
      #   right:              blog
      comments:             # true
      share:                true
      related:              true
      # mailchimp:            true
      navbar:
        transparent:        true
        transparent_color:  light
      header:
        layout:             center
        background_overlay: "rgba(0, 0, 0, 0.5)"
        color:              light
        header_size:        large
        heading_size:       medium
        parallax:           true
  # _pages
  - scope:
      path:                 ""
      type:                 pages
    values:
      layout:               page
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc