# Site settings
title: Open Accessibility
email: elias.pajares@tum.de
description: >
  Here you can work with the dynamic, interactive  and open 
  accessibility planning tool GOAT. This makes it a great instrument for walking and cycling. 
    
lang: en-US

destination: "./_site"

git_address: https://github.com/goat-community/goat
linkedin_address: https://www.linkedin.com/company/goat-tool/
twitter_address: https://twitter.com/GoatTool

appURL: https://open-accessibility.org/versions
git_edit_address: https://github.com/goat-community/goat-website

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  videos:
    output: false
  versions:
    output: false
